openapi: 3.0.3
info:
  title: STD23052 - TD4
  version: '1.0.2'
servers:
  - url: https://localhost.std23052.com
paths:
  /customers/{customerId}/orders:
    get:
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste des commandes du client
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

    post:
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                meals:
                  type: array
                  items:
                    type: object
                    properties:
                      mealId:
                        type: string
                      quantity:
                        type: integer
      required: true
      responses:
        200:
          description: Commande créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /customers/{customerId}/orders/{orderId}:
    put:
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                meals:
                  type: array
                  items:
                    type: object
                    properties:
                      mealId:
                        type: string
                      quantity:
                        type: integer
      required: true
      responses:
        200:
          description: Commande modifiée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        reference:
          type: string
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: './TD3-v1-std23052.yaml#/components/schemas/Meal'
              quantity:
                type: integer
        orderDatetime:
          type: string
          format: date-time
